export const API_URLS = {
    HTTP : "http://",
    HTTPS : "https://",
    DOMAIN : "localhost",
    COLON : ":",
    PORT : "3000",
    ENDPOINTS : {
        API_USER_CHECK_USERNAME : "/api/user/check-username",
        API_USER_CREATE_USER : "/api/user/create-user",
        API_ADMIN_LISTS_USERS : "/api/admin-dashboard/list-users",
        API_ADMIN_UPDATES_USER : "/api/admin-dashboard/admin-updates-user",
        API_ADMIN_DELETES_USER : "/api/admin-dashboard/admin-deletes-user"
    }
};

export const API_ENDPOINTS = {
    CHECK_USERNAME : `${API_URLS.HTTP}${API_URLS.DOMAIN}${API_URLS.COLON}${API_URLS.PORT}${API_URLS.ENDPOINTS.API_USER_CHECK_USERNAME}`,
    CREATE_USER : `${API_URLS.HTTP}${API_URLS.DOMAIN}${API_URLS.COLON}${API_URLS.PORT}${API_URLS.ENDPOINTS.API_USER_CREATE_USER}`,
    ADMIN_LISTS_USERS : `${API_URLS.HTTP}${API_URLS.DOMAIN}${API_URLS.COLON}${API_URLS.PORT}${API_URLS.ENDPOINTS.API_ADMIN_LISTS_USERS}`,
    ADMIN_UPDATES_USER : `${API_URLS.HTTP}${API_URLS.DOMAIN}${API_URLS.COLON}${API_URLS.PORT}${API_URLS.ENDPOINTS.API_ADMIN_UPDATES_USER}`,
    ADMIN_DELETES_USER : `${API_URLS.HTTP}${API_URLS.DOMAIN}${API_URLS.COLON}${API_URLS.PORT}${API_URLS.ENDPOINTS.API_ADMIN_DELETES_USER}`

};